name: PR Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Chrome Browser
        run: |
          sudo apt-get install chromium-browser

      - name: Install NPM Dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Delete folder and replace with master branch
        run: |
          pwd
          rm -rf ./__tests__
          git checkout main __tests__
          ls -a

      - name: Run test script
        run: |
          npm start &
          sleep 20
          npm run test
