name: PR Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Install Chrome Browser
        run: |
          npx puppeteer browsers install chrome

      - name: Delete folder and replace with master branch
        run: |
          pwd
          rm -rf ./__tests__
          git checkout main __tests__
          ls -a

      - name: Run test script
        run: |
          npm start &
          sleep 20
          echo "Sleep completed"
          npm run test
