name: PR Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setting up env vars
        run: |
          echo "
          REACT_APP_API_KEY= ${{secrets.API_KEY}}
          REACT_APP_AUTH_DOMAIN= ${{secrets.AUTH_DOMAIN}}
          REACT_APP_PROJECT_ID= ${{secrets.PROJECT_ID}}
          REACT_APP_STORAGE_BUCKET= ${{secrets.STORAGE_BUCKET}}
          REACT_APP_MESSAGING_SENDER_ID= ${{secrets.MESSAGING_SENDER_ID}}
          REACT_APP_APP_ID= ${{secrets.APP_ID}}
          REACT_APP_MEASUREMENT_ID= ${{secrets.MEASUREMENT_ID}}
          " >> .env

      - name: Install NPM Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: Install Chrome Browser
        run: |
          npx puppeteer browsers install chrome

      - name: Delete folder and replace with master branch
        run: |
          rm -rf ./__tests__
          git checkout main __tests__

      - name: Run test script
        run: |
          npm start &
          sleep 20
          git rev-parse --abbrev-ref HEAD
          echo "Sleep completed"
          npm run test

      # - name: Updating the results on the backend
      #   run: |
      #     curl
